document.writeln("<!DOCTYPE html>");
document.writeln("<html dir=\'ltr\' lang=\'en-US\'>");
document.writeln("<body>");
document.writeln("<div id=\'triangle-down\'>&nbsp;</div>");
document.writeln("<!-- Footer Start -->");
document.writeln("");
document.writeln("<section id=\'footer_wrap\'>");
document.writeln("");
document.writeln("<footer>");
document.writeln("");
document.writeln("    <div class=\'one_fourth\'>");
document.writeln("");
document.writeln("    <div class=\'widget_container\'>");
document.writeln("");
document.writeln("    ");
document.writeln("    </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'one_fourth_last\'>");
document.writeln("");
document.writeln("    <div class=\'widget_container flick_widget\'>");
document.writeln("");
document.writeln("        ");
document.writeln("           </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("    <div class=\'bottom_sec\'>");
document.writeln("");
document.writeln("        <span>Copyright &copy; Kayapati 2012</span>");
document.writeln("");
document.writeln("        <ul>");
document.writeln("");
document.writeln("          ");
document.writeln("        </ul>");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("</footer>");
document.writeln("");
document.writeln("</section>");
document.writeln("");
document.writeln("<!-- Footer End -->");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");