

document.writeln("");
document.writeln("<meta name=\'viewport\' content=\'initial-scale=1, maximum-scale=1\' />");
document.writeln("<meta name=\'viewport\' content=\'width=device-width\' />");
document.writeln("<title>I Folio A Responsive HTML5 Template </title>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/reset.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/layout.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/jqueryslidemenu.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/quicksand.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/widget.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/hoverdir.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'style.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/responsive.css\' />");

document.writeln("<script type=\'text/javascript\' src=\'js/jquery-1.8.1.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'js/jqueryslidemenu.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'js/jquery.easing.1.3.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'js/portfolio_sortable.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'js/quicksand.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'js/custom.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'js/jquery.hoverdir.js\'></script>");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("//Image Hover");
document.writeln("jQuery(document).ready(function(){");
document.writeln("jQuery(function() {");
document.writeln("	jQuery(\'#list > li\').hoverdir();");
document.writeln("});");
document.writeln("});");
document.writeln("</script>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' /></head>");
document.writeln("<!--[if lt IE 9]>");
document.writeln("<script src=\'http://html5shim.googlecode.com/svn/trunk/html5.js\'></script>");
document.writeln("<![endif]-->");
document.writeln("<!--[if lt IE 9]>");
document.writeln("	<script src=\'http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js\'></script>");
document.writeln("<![endif]-->");
document.writeln("<body>");
document.writeln("<!-- Header Start -->");
document.writeln("<section id=\'header_wrap\'>");
document.writeln("<nav id=\'myslidemenu\' class=\'jqueryslidemenu clearfix\'>");
document.writeln("    <ul>");
document.writeln("        <li><a class=\'active\' href=\'index.html\'>首页</a></li>");
document.writeln("        <li><a href=\'about.html\'>关于我们</a></li>");
document.writeln("        <li><a href=\''\>公式模板</a>");
document.writeln("        <ul>");
document.writeln("            <li><a href=\'math.html\'>数学</a></li>");
document.writeln("            <li><a href=\'end.html\'>物理</a></li>");
document.writeln("            <li><a href=\'end.html\'>其他</a></li>");
document.writeln("        </ul>");
document.writeln("        </li>");
document.writeln("        ");
document.writeln("        <li><a href=\''\>公式汇总</a>");

document.writeln("        <ul>");
document.writeln("            <li><a href=\'calculus.html\'>高数</a></li>");
document.writeln("            <li><a href=\'end.html\'>大物</a></li>");
document.writeln("            <li><a href=\'end.html\'>其他</a></li>");
document.writeln("        </ul>");
document.writeln("        </li>");
document.writeln("        <li><a href=\'contact.html\'>联系我们</a></li>");
document.writeln("    </ul>");
document.writeln("</nav>");
document.writeln("</section>");
document.writeln("<!-- Header End -->");
document.writeln("<!-- Logo Start -->");
document.writeln("");
document.writeln("<figure><a href=\'index.html\'><img src=\'images/logo.png\' alt=\'img\' /></a></figure> ");
document.writeln("");
document.writeln("<!-- Logo End -->");
document.writeln("");
document.writeln("<div id=\'triangle-up\'></div>");

